export const PricingDataDev = {
	"prod_Nzu7DOI4NFo7oJ|year": {
		prodId: "prod_Nzu7DOI4NFo7oJ",
		prodName: "Teleseer Teams (2 TB)",
		cost: 4798800,
		interval: "year",
		priceId: "price_1NDuJTGUyP9kXnfZQH6KYQMI",
		link: "https://checkout.teleseer.com/b/test_3cs3gdaQ39Oi0veaHC",
	},
	"prod_Nzu6QIbyqEspSP|year": {
		prodId: "prod_Nzu6QIbyqEspSP",
		prodName: "Teleseer Teams (1 TB)",
		cost: 3598800,
		interval: "year",
		priceId: "price_1NDuIlGUyP9kXnfZyGPWytSm",
		link: "https://checkout.teleseer.com/b/test_fZe7wtcYb2lQem42b7",
	},
	"prod_Nzu7DOI4NFo7oJ|month": {
		prodId: "prod_Nzu7DOI4NFo7oJ",
		prodName: "Teleseer Teams (2 TB)",
		cost: 499900,
		interval: "month",
		priceId: "price_1NDuJTGUyP9kXnfZAlwm7vKB",
		link: "https://checkout.teleseer.com/b/test_9AQ5ol5vJe4y1zi8zw",
	},
	"prod_Nzu55ZREPKt702|year": {
		prodId: "prod_Nzu55ZREPKt702",
		prodName: "Teleseer Teams (500 GB)",
		cost: 1798800,
		interval: "year",
		priceId: "price_1NDuHVGUyP9kXnfZB4reBa8B",
		link: "https://checkout.teleseer.com/b/test_5kAdURe2fgcGb9S031",
	},
	"prod_Nzu6QIbyqEspSP|month": {
		prodId: "prod_Nzu6QIbyqEspSP",
		prodName: "Teleseer Teams (1 TB)",
		cost: 374900,
		interval: "month",
		priceId: "price_1NDuIlGUyP9kXnfZrenQLBW6",
		link: "https://checkout.teleseer.com/b/test_7sI9EB5vJf8C0ve9DC",
	},
	"prod_MeU7Sd8NfyG2y1|year": {
		prodId: "prod_MeU7Sd8NfyG2y1",
		prodName: "Teleseer Teams (300 GB)",
		cost: 1198800,
		interval: "year",
		priceId: "price_1NDuFPGUyP9kXnfZyosmw37t",
		link: "https://checkout.teleseer.com/b/test_28odUR4rF0dI3Hq6rr",
	},
	"prod_Nzu55ZREPKt702|month": {
		prodId: "prod_Nzu55ZREPKt702",
		prodName: "Teleseer Teams (500 GB)",
		cost: 187400,
		interval: "month",
		priceId: "price_1NDuHVGUyP9kXnfZyxZrf582",
		link: "https://checkout.teleseer.com/b/test_7sI7wt9LZ9Oib9SbLM",
	},
	"prod_NzcRQX2e3RYkuw|year": {
		prodId: "prod_NzcRQX2e3RYkuw",
		prodName: "Teleseer Pro (150 GB)",
		cost: 718800,
		interval: "year",
		priceId: "price_1NDdCyGUyP9kXnfZd8ms5P5F",
		link: "https://checkout.teleseer.com/b/test_5kAcQN6zN2lQ1zi4jl",
	},
	"prod_MeU7Sd8NfyG2y1|month": {
		prodId: "prod_MeU7Sd8NfyG2y1",
		prodName: "Teleseer Teams (300 GB)",
		cost: 124900,
		interval: "month",
		priceId: "price_1NDuF1GUyP9kXnfZq8NlBxgP",
		link: "https://checkout.teleseer.com/b/test_dR65olcYbe4ya5ObLO",
	},
	"prod_MeU7K4Gq8jKxec|year": {
		prodId: "prod_MeU7K4Gq8jKxec",
		prodName: "Teleseer Pro (100 GB)",
		cost: 478800,
		interval: "year",
		priceId: "price_1NDdBDGUyP9kXnfZMvNkhI3a",
		link: "https://checkout.teleseer.com/b/test_cN2g2Z3nB5y2guc17b",
	},
	"prod_MeU7K4Gq8jKxec|month": {
		prodId: "prod_MeU7K4Gq8jKxec",
		prodName: "Teleseer Pro (100 GB)",
		cost: 49900,
		interval: "month",
		priceId: "price_1NDdAoGUyP9kXnfZt3Hoe5rk",
		link: "https://checkout.teleseer.com/b/test_14kcQNganbWq1zibLR",
	},
	"prod_NzcOkvKcfwEJDA|year": {
		prodId: "prod_NzcOkvKcfwEJDA",
		prodName: "Teleseer Pro (75 GB)",
		cost: 358800,
		interval: "year",
		priceId: "price_1NDd9jGUyP9kXnfZgYu2SHyc",
		link: "https://checkout.teleseer.com/b/test_4gwbMJ9LZ1hM91K8zE",
	},
	"prod_NzcRQX2e3RYkuw|month": {
		prodId: "prod_NzcRQX2e3RYkuw",
		prodName: "Teleseer Pro (150 GB)",
		cost: 74900,
		interval: "month",
		priceId: "price_1NDdCyGUyP9kXnfZu4AmyOGn",
		link: "https://checkout.teleseer.com/b/test_eVa2c95vJ5y2cdW03a",
	},
	"prod_Nzat4nsV0oAz24|year": {
		prodId: "prod_Nzat4nsV0oAz24",
		prodName: "Teleseer Starter (20 GB)",
		cost: 190800,
		interval: "year",
		priceId: "price_1NDbhRGUyP9kXnfZdWHei8TS",
		link: "https://checkout.teleseer.com/b/test_dR61856zN6C6em4bLT",
	},
	"prod_NzcOkvKcfwEJDA|month": {
		prodId: "prod_NzcOkvKcfwEJDA",
		prodName: "Teleseer Pro (75 GB)",
		cost: 37400,
		interval: "month",
		priceId: "price_1NDd9jGUyP9kXnfZJzS0Ytj1",
		link: "https://checkout.teleseer.com/b/test_9AQ0419LZ9Oi4Lu7vE",
	},
	"prod_Nzarmn4e78EXz2|year": {
		prodId: "prod_Nzarmn4e78EXz2",
		prodName: "Teleseer Starter (5 GB)",
		cost: 46800,
		interval: "year",
		priceId: "price_1NDbg2GUyP9kXnfZDNKspRz6",
		link: "https://checkout.teleseer.com/b/test_28oeYV8HVgcG6TCbLV",
	},
	"prod_Nzat4nsV0oAz24|month": {
		prodId: "prod_Nzat4nsV0oAz24",
		prodName: "Teleseer Starter (20 GB)",
		cost: 19900,
		interval: "month",
		priceId: "price_1NDbhRGUyP9kXnfZ8b8eNONw",
		link: "https://checkout.teleseer.com/b/test_cN28Ax4rF7GacdW2bm",
	},
	"prod_NzaoJMCcrvfdBl|year": {
		prodId: "prod_NzaoJMCcrvfdBl",
		prodName: "Teleseer Starter (2 GB)",
		cost: 18000,
		interval: "year",
		priceId: "price_1NDbcfGUyP9kXnfZHxbdBWbF",
		link: "https://checkout.teleseer.com/b/test_4gwbMJ4rFaSmguc5nz",
	},
	"prod_NzaoJMCcrvfdBl|month": {
		prodId: "prod_NzaoJMCcrvfdBl",
		prodName: "Teleseer Starter (2 GB)",
		cost: 1900,
		interval: "month",
		priceId: "price_1NDbcfGUyP9kXnfZrgMYd3o0",
		link: "https://checkout.teleseer.com/b/test_00gaIFganbWq1zidU6",
	},
	"prod_NMdZCgj8c3lABb|year": {
		prodId: "prod_NMdZCgj8c3lABb",
		prodName: "Teleseer Pro (50 GB)",
		cost: 238800,
		interval: "year",
		priceId: "price_1Mbug7GUyP9kXnfZDTdgJevB",
		link: "https://checkout.teleseer.com/b/test_6oE041gan2lQcdW16X",
	},
	"prod_NMdZCgj8c3lABb|month": {
		prodId: "prod_NMdZCgj8c3lABb",
		prodName: "Teleseer Pro (50 GB)",
		cost: 24900,
		interval: "month",
		priceId: "price_1MbuIpGUyP9kXnfZDOe0MyjH",
		link: "https://checkout.teleseer.com/b/test_14k4kh8HVgcG4Lu3f3",
	},
	"prod_Nzarmn4e78EXz2|month": {
		prodId: "prod_Nzarmn4e78EXz2",
		prodName: "Teleseer Starter (5 GB)",
		cost: 4900,
		interval: "month",
		priceId: "price_1NDbg2GUyP9kXnfZsiSIJSKU",
		link: "https://checkout.teleseer.com/b/test_eVa1852jxd0u6TCdU7",
	},
	"prod_NK6dRgnmymlqGS|year": {
		prodId: "prod_NK6dRgnmymlqGS",
		prodName: "Teleseer Starter (10 GB)",
		cost: 94800,
		interval: "year",
		priceId: "price_1MZSPlGUyP9kXnfZVCALh38V",
		link: "https://checkout.teleseer.com/b/test_dR6bMJaQ35y2cdWaHu",
	},
	"prod_NK6dRgnmymlqGS|month": {
		prodId: "prod_NK6dRgnmymlqGS",
		prodName: "Teleseer Starter (10 GB)",
		cost: 9900,
		interval: "month",
		priceId: "price_1MZSPlGUyP9kXnfZlmsCzuJb",
		link: "https://checkout.teleseer.com/b/test_5kAeYV2jxbWqem416T",
	},
}
export const ProductDataDev = {
	object: "list",
	data: [
		{
			id: "prod_Nzu7DOI4NFo7oJ",
			object: "product",
			active: true,
			attributes: [],
			created: 1685559842,
			default_price: "price_1NDuJTGUyP9kXnfZAlwm7vKB",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Teams (2 TB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685559844,
			url: null,
		},
		{
			id: "prod_Nzu6QIbyqEspSP",
			object: "product",
			active: true,
			attributes: [],
			created: 1685559798,
			default_price: "price_1NDuIlGUyP9kXnfZrenQLBW6",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Teams (1 TB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685559800,
			url: null,
		},
		{
			id: "prod_Nzu55ZREPKt702",
			object: "product",
			active: true,
			attributes: [],
			created: 1685559720,
			default_price: "price_1NDuHVGUyP9kXnfZyxZrf582",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Teams (500 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685559722,
			url: null,
		},
		{
			id: "prod_NzcRQX2e3RYkuw",
			object: "product",
			active: true,
			attributes: [],
			created: 1685494091,
			default_price: "price_1NDdCyGUyP9kXnfZu4AmyOGn",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Pro (150 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685494092,
			url: null,
		},
		{
			id: "prod_NzcOkvKcfwEJDA",
			object: "product",
			active: true,
			attributes: [],
			created: 1685493891,
			default_price: "price_1NDd9jGUyP9kXnfZJzS0Ytj1",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Pro (75 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685493892,
			url: null,
		},
		{
			id: "prod_Nzat4nsV0oAz24",
			object: "product",
			active: true,
			attributes: [],
			created: 1685488293,
			default_price: "price_1NDbhRGUyP9kXnfZ8b8eNONw",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Starter (20 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685488294,
			url: null,
		},
		{
			id: "prod_Nzarmn4e78EXz2",
			object: "product",
			active: true,
			attributes: [],
			created: 1685488205,
			default_price: "price_1NDbg2GUyP9kXnfZsiSIJSKU",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Starter (5 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685488206,
			url: null,
		},
		{
			id: "prod_NzaoJMCcrvfdBl",
			object: "product",
			active: true,
			attributes: [],
			created: 1685487997,
			default_price: "price_1NDbcfGUyP9kXnfZrgMYd3o0",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Starter (2 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685487998,
			url: null,
		},
		{
			id: "prod_NMdZCgj8c3lABb",
			object: "product",
			active: true,
			attributes: [],
			created: 1676503338,
			default_price: "price_1MbuIpGUyP9kXnfZDOe0MyjH",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Pro (50 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1676504784,
			url: null,
		},
		{
			id: "prod_NK6dRgnmymlqGS",
			object: "product",
			active: true,
			attributes: [],
			created: 1675919480,
			default_price: "price_1MZSPlGUyP9kXnfZlmsCzuJb",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Starter (10 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1675919482,
			url: null,
		},
		{
			id: "prod_MeU7Sd8NfyG2y1",
			object: "product",
			active: true,
			attributes: [],
			created: 1666320013,
			default_price: "price_1NDuF1GUyP9kXnfZq8NlBxgP",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Teams (300 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685559642,
			url: null,
		},
		{
			id: "prod_MeU7K4Gq8jKxec",
			object: "product",
			active: true,
			attributes: [],
			created: 1666319977,
			default_price: "price_1NDdAoGUyP9kXnfZt3Hoe5rk",
			description: null,
			images: [],
			livemode: false,
			metadata: {},
			name: "Teleseer Pro (100 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1685493989,
			url: null,
		},
	],
	has_more: false,
	url: "/v1/products",
}
export const ProductPriceDataDev = {
	object: "list",
	data: [
		{
			id: "price_1NDuJTGUyP9kXnfZQH6KYQMI",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685559843,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzu7DOI4NFo7oJ",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 4798800,
			unit_amount_decimal: "4798800",
		},
		{
			id: "price_1NDuJTGUyP9kXnfZAlwm7vKB",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685559843,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzu7DOI4NFo7oJ",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 499900,
			unit_amount_decimal: "499900",
		},
		{
			id: "price_1NDuIlGUyP9kXnfZyGPWytSm",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685559799,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzu6QIbyqEspSP",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 3598800,
			unit_amount_decimal: "3598800",
		},
		{
			id: "price_1NDuIlGUyP9kXnfZrenQLBW6",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685559799,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzu6QIbyqEspSP",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 374900,
			unit_amount_decimal: "374900",
		},
		{
			id: "price_1NDuHVGUyP9kXnfZB4reBa8B",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685559721,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzu55ZREPKt702",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 1798800,
			unit_amount_decimal: "1798800",
		},
		{
			id: "price_1NDuHVGUyP9kXnfZyxZrf582",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685559721,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzu55ZREPKt702",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 187400,
			unit_amount_decimal: "187400",
		},
		{
			id: "price_1NDuFPGUyP9kXnfZyosmw37t",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685559591,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MeU7Sd8NfyG2y1",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 1198800,
			unit_amount_decimal: "1198800",
		},
		{
			id: "price_1NDuF1GUyP9kXnfZq8NlBxgP",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685559567,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MeU7Sd8NfyG2y1",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 124900,
			unit_amount_decimal: "124900",
		},
		{
			id: "price_1NDdCyGUyP9kXnfZd8ms5P5F",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685494092,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NzcRQX2e3RYkuw",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 718800,
			unit_amount_decimal: "718800",
		},
		{
			id: "price_1NDdCyGUyP9kXnfZu4AmyOGn",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685494092,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NzcRQX2e3RYkuw",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 74900,
			unit_amount_decimal: "74900",
		},
		{
			id: "price_1NDdBDGUyP9kXnfZMvNkhI3a",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685493983,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MeU7K4Gq8jKxec",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 478800,
			unit_amount_decimal: "478800",
		},
		{
			id: "price_1NDdAoGUyP9kXnfZt3Hoe5rk",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685493958,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MeU7K4Gq8jKxec",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 49900,
			unit_amount_decimal: "49900",
		},
		{
			id: "price_1NDd9jGUyP9kXnfZgYu2SHyc",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685493891,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NzcOkvKcfwEJDA",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 358800,
			unit_amount_decimal: "358800",
		},
		{
			id: "price_1NDd9jGUyP9kXnfZJzS0Ytj1",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685493891,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NzcOkvKcfwEJDA",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 37400,
			unit_amount_decimal: "37400",
		},
		{
			id: "price_1NDbhRGUyP9kXnfZdWHei8TS",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685488293,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzat4nsV0oAz24",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 190800,
			unit_amount_decimal: "190800",
		},
		{
			id: "price_1NDbhRGUyP9kXnfZ8b8eNONw",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685488293,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzat4nsV0oAz24",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 19900,
			unit_amount_decimal: "19900",
		},
		{
			id: "price_1NDbg2GUyP9kXnfZDNKspRz6",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685488206,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzarmn4e78EXz2",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 46800,
			unit_amount_decimal: "46800",
		},
		{
			id: "price_1NDbg2GUyP9kXnfZsiSIJSKU",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685488206,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Nzarmn4e78EXz2",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 4900,
			unit_amount_decimal: "4900",
		},
		{
			id: "price_1NDbcfGUyP9kXnfZHxbdBWbF",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685487997,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NzaoJMCcrvfdBl",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 18000,
			unit_amount_decimal: "18000",
		},
		{
			id: "price_1NDbcfGUyP9kXnfZrgMYd3o0",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1685487997,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NzaoJMCcrvfdBl",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 1900,
			unit_amount_decimal: "1900",
		},
		{
			id: "price_1MbuiLGUyP9kXnfZuaYseJ6h",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676504921,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfF9dP3mPJBGtV",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 478800,
			unit_amount_decimal: "478800",
		},
		{
			id: "price_1Mbui9GUyP9kXnfZ6JPPOdbl",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676504909,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfF9dP3mPJBGtV",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 49900,
			unit_amount_decimal: "49900",
		},
		{
			id: "price_1Mbug7GUyP9kXnfZDTdgJevB",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676504783,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NMdZCgj8c3lABb",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 238800,
			unit_amount_decimal: "238800",
		},
		{
			id: "price_1MbuIpGUyP9kXnfZDOe0MyjH",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676503339,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NMdZCgj8c3lABb",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 24900,
			unit_amount_decimal: "24900",
		},
		{
			id: "price_1MZSPlGUyP9kXnfZVCALh38V",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1675919481,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NK6dRgnmymlqGS",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 94800,
			unit_amount_decimal: "94800",
		},
		{
			id: "price_1MZSPlGUyP9kXnfZlmsCzuJb",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1675919481,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NK6dRgnmymlqGS",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 9900,
			unit_amount_decimal: "9900",
		},
		{
			id: "price_1LxM2sGUyP9kXnfZhurRbNni",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666838534,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfFAyBr9OXVxJG",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 200,
			unit_amount_decimal: "200",
		},
		{
			id: "price_1LwTSMGUyP9kXnfZAiIy7JVY",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666628694,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Mfp675y5buS6Dz",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 1000000,
			unit_amount_decimal: "1000000",
		},
		{
			id: "price_1LwTSMGUyP9kXnfZIsNoZr0u",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666628694,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_Mfp675y5buS6Dz",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 100000,
			unit_amount_decimal: "100000",
		},
		{
			id: "price_1LwCryGUyP9kXnfZRr4N3O1J",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666564934,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfXxSuamSPXBTR",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "unspecified",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 1500,
			unit_amount_decimal: "1500",
		},
		{
			id: "price_1Lvug0GUyP9kXnfZgGGPuE3u",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666495000,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfFAyBr9OXVxJG",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 478800,
			unit_amount_decimal: "478800",
		},
		{
			id: "price_1Lvug0GUyP9kXnfZaE1xiyoD",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666495000,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfFAyBr9OXVxJG",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 49900,
			unit_amount_decimal: "49900",
		},
		{
			id: "price_1Lvua5GUyP9kXnfZQE2OZhKQ",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666494633,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfF4EP6muijTDC",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 94800,
			unit_amount_decimal: "94800",
		},
		{
			id: "price_1Lvua5GUyP9kXnfZju3MiPzP",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666494633,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfF4EP6muijTDC",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 9900,
			unit_amount_decimal: "9900",
		},
		{
			id: "price_1LvBM9GUyP9kXnfZf0EAbcEH",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666320789,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MeU6p5nJCScRjT",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 46800,
			unit_amount_decimal: "46800",
		},
		{
			id: "price_1LvB7tGUyP9kXnfZCRH5cBMi",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666319905,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MeU6p5nJCScRjT",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 4900,
			unit_amount_decimal: "4900",
		},
	],
	has_more: false,
	url: "/v1/prices",
}
export const PaymentLinkDataDev = {
	object: "list",
	data: [
		{
			id: "plink_1MbugHGUyP9kXnfZQh4fu79q",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://dev.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: false,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/test_6oE041gan2lQcdW16X",
		},
		{
			id: "plink_1MbuR8GUyP9kXnfZPnuYj9Pc",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://dev.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: false,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/test_14k4kh8HVgcG4Lu3f3",
		},
		{
			id: "plink_1MaRH0GUyP9kXnfZxXxDzyz4",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://dev.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: false,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/test_dR6bMJaQ35y2cdWaHu",
		},
		{
			id: "plink_1MaRGzGUyP9kXnfZ2dRb7DL3",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://dev.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: false,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/test_5kAeYV2jxbWqem416T",
		},
		{
			id: "plink_1LwZvpGUyP9kXnfZo5yrD0vi",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://dev.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: { promotions: "none", terms_of_service: "none" },
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: false,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/test_eVaaIF8HVd0ua5O3eS",
		},
	],
	has_more: false,
	url: "/v1/payment_links",
}

export const PricingDataProd = {
	"prod_MfuUY9YItO6jKO|month": {
		prodId: "prod_MfuUY9YItO6jKO",
		prodName: "Teleseer Pro (100 GB)",
		cost: 37900,
		interval: "month",
		priceId: "price_1MbuLQGUyP9kXnfZWc68P4Z8",
		link: "https://checkout.teleseer.com/b/8wMaFM6re2ssgV229R",
	},
	"prod_NMdamx0fJNKkDf|year": {
		prodId: "prod_NMdamx0fJNKkDf",
		prodName: "Teleseer Pro (50 GB)",
		cost: 238800,
		interval: "year",
		priceId: "price_1MbuIwGUyP9kXnfZtAOs6kpD",
		link: "https://checkout.teleseer.com/b/6oEdRY7viffebAI01F",
	},
	"prod_MfuUl19Z99KKuR|month": {
		prodId: "prod_MfuUl19Z99KKuR",
		prodName: "Teleseer Pro (200 GB)",
		cost: 49900,
		interval: "month",
		priceId: "price_1MbuNAGUyP9kXnfZIuXItXgQ",
		link: "https://checkout.teleseer.com/b/7sI4ho5na8QQgV2bKo",
	},
	"prod_MfuUl19Z99KKuR|year": {
		prodId: "prod_MfuUl19Z99KKuR",
		prodName: "Teleseer Pro (200 GB)",
		cost: 478800,
		interval: "year",
		priceId: "price_1MbuMxGUyP9kXnfZFhnHNwEa",
		link: "https://checkout.teleseer.com/b/4gwdRY6re7MM34c3dW",
	},
	"prod_MfuUHskBj85gTF|year": {
		prodId: "prod_MfuUHskBj85gTF",
		prodName: "Teleseer Starter (5 GB)",
		cost: 46800,
		interval: "year",
		priceId: "price_1LwYfQGUyP9kXnfZyrsyrxP8",
		link: "https://checkout.teleseer.com/b/9AQeW2bLyaYYdIQ8yh",
	},
	"prod_NMdamx0fJNKkDf|month": {
		prodId: "prod_NMdamx0fJNKkDf",
		prodName: "Teleseer Pro (50 GB)",
		cost: 24900,
		interval: "month",
		priceId: "price_1MbuIwGUyP9kXnfZwZyq2dic",
		link: "https://checkout.teleseer.com/b/6oE3dk8zmgji8owbKm",
	},
	"prod_NMXm7zGLj81wvL|month": {
		prodId: "prod_NMXm7zGLj81wvL",
		prodName: "Teleseer Starter (10 GB)",
		cost: 9900,
		interval: "month",
		priceId: "price_1MbohCGUyP9kXnfZQBudm5Fx",
		link: "https://checkout.teleseer.com/b/8wM9BI7vi5EEfQY6q0",
	},
	"prod_NMXm7zGLj81wvL|year": {
		prodId: "prod_NMXm7zGLj81wvL",
		prodName: "Teleseer Starter (10 GB)",
		cost: 94800,
		interval: "year",
		priceId: "price_1MbohBGUyP9kXnfZmMJ3pPY9",
		link: "https://checkout.teleseer.com/b/6oE7tAbLyebacEMcOp",
	},
	"prod_MfuUY9YItO6jKO|year": {
		prodId: "prod_MfuUY9YItO6jKO",
		prodName: "Teleseer Pro (100 GB)",
		cost: 358800,
		interval: "year",
		priceId: "price_1MbuM1GUyP9kXnfZ2gn21tUy",
		link: "https://checkout.teleseer.com/b/4gw8xEcPC9UU0W44hX",
	},
	"prod_MfuUHskBj85gTF|month": {
		prodId: "prod_MfuUHskBj85gTF",
		prodName: "Teleseer Starter (5 GB)",
		cost: 4900,
		interval: "month",
		priceId: "price_1LwYfQGUyP9kXnfZn0jE8QaE",
		link: "https://checkout.teleseer.com/b/3csbJQbLy6II6goaGm",
	},
}
export const ProductDataProd = {
	object: "list",
	data: [
		{
			id: "prod_NMdamx0fJNKkDf",
			object: "product",
			active: true,
			attributes: [],
			created: 1676503346,
			default_price: "price_1MbuIwGUyP9kXnfZwZyq2dic",
			description: null,
			images: [],
			livemode: true,
			metadata: {},
			name: "Teleseer Pro (50 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1676503346,
			url: null,
		},
		{
			id: "prod_NMXm7zGLj81wvL",
			object: "product",
			active: true,
			attributes: [],
			created: 1676481785,
			default_price: "price_1MbohCGUyP9kXnfZQBudm5Fx",
			description: null,
			images: [],
			livemode: true,
			metadata: {},
			name: "Teleseer Starter (10 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1676481786,
			url: null,
		},
		{
			id: "prod_Mfuxsa5JWXtFO6",
			object: "product",
			active: true,
			attributes: [],
			created: 1666650495,
			default_price: null,
			description: null,
			images: [],
			livemode: true,
			metadata: {},
			name: "Teleseer Team (500 GB per user)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10000000",
			type: "service",
			unit_label: null,
			updated: 1676505056,
			url: null,
		},
		{
			id: "prod_MfuUHskBj85gTF",
			object: "product",
			active: true,
			attributes: [],
			created: 1666648724,
			default_price: "price_1LwYfQGUyP9kXnfZyrsyrxP8",
			description: null,
			images: [],
			livemode: true,
			metadata: {},
			name: "Teleseer Starter (5 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10103001",
			type: "service",
			unit_label: null,
			updated: 1676503620,
			url: null,
		},
		{
			id: "prod_MfuUY9YItO6jKO",
			object: "product",
			active: true,
			attributes: [],
			created: 1666648712,
			default_price: "price_1MbuM1GUyP9kXnfZ2gn21tUy",
			description: null,
			images: [],
			livemode: true,
			metadata: {},
			name: "Teleseer Pro (100 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10103001",
			type: "service",
			unit_label: null,
			updated: 1676503538,
			url: null,
		},
		{
			id: "prod_MfuUl19Z99KKuR",
			object: "product",
			active: true,
			attributes: [],
			created: 1666648701,
			default_price: "price_1MbuMxGUyP9kXnfZFhnHNwEa",
			description: null,
			images: [],
			livemode: true,
			metadata: {},
			name: "Teleseer Pro (200 GB)",
			package_dimensions: null,
			shippable: null,
			statement_descriptor: null,
			tax_code: "txcd_10103001",
			type: "service",
			unit_label: null,
			updated: 1676503609,
			url: null,
		},
	],
	has_more: false,
	url: "/v1/products",
}
export const ProductPriceDataProd = {
	object: "list",
	data: [
		{
			id: "price_1MbuNAGUyP9kXnfZIuXItXgQ",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676503608,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUl19Z99KKuR",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 49900,
			unit_amount_decimal: "49900",
		},
		{
			id: "price_1MbuMxGUyP9kXnfZFhnHNwEa",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676503595,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUl19Z99KKuR",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 478800,
			unit_amount_decimal: "478800",
		},
		{
			id: "price_1MbuM1GUyP9kXnfZ2gn21tUy",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676503537,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUY9YItO6jKO",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 358800,
			unit_amount_decimal: "358800",
		},
		{
			id: "price_1MbuLQGUyP9kXnfZWc68P4Z8",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676503500,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUY9YItO6jKO",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 37900,
			unit_amount_decimal: "37900",
		},
		{
			id: "price_1MbuIwGUyP9kXnfZtAOs6kpD",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676503346,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NMdamx0fJNKkDf",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 238800,
			unit_amount_decimal: "238800",
		},
		{
			id: "price_1MbuIwGUyP9kXnfZwZyq2dic",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676503346,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NMdamx0fJNKkDf",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 24900,
			unit_amount_decimal: "24900",
		},
		{
			id: "price_1MbohCGUyP9kXnfZQBudm5Fx",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676481786,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NMXm7zGLj81wvL",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 9900,
			unit_amount_decimal: "9900",
		},
		{
			id: "price_1MbohBGUyP9kXnfZmMJ3pPY9",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676481785,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_NMXm7zGLj81wvL",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 94800,
			unit_amount_decimal: "94800",
		},
		{
			id: "price_1MZxf3GUyP9kXnfZ8Zn8tvFk",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1676039593,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUDm2rcXbhbj",
			recurring: null,
			tax_behavior: "inclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "one_time",
			unit_amount: 94800,
			unit_amount_decimal: "94800",
		},
		{
			id: "price_1LxM4NGUyP9kXnfZWicGU3I9",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666838627,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfpQXEGqW8HjMR",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 200,
			unit_amount_decimal: "200",
		},
		{
			id: "price_1LwYfQGUyP9kXnfZn0jE8QaE",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666648724,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUHskBj85gTF",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 4900,
			unit_amount_decimal: "4900",
		},
		{
			id: "price_1LwYfQGUyP9kXnfZyrsyrxP8",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666648724,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUHskBj85gTF",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 46800,
			unit_amount_decimal: "46800",
		},
		{
			id: "price_1LwYfAGUyP9kXnfZWQYFVyOy",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666648708,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUDm2rcXbhbj",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 9900,
			unit_amount_decimal: "9900",
		},
		{
			id: "price_1LwYf9GUyP9kXnfZL4igVk9W",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666648707,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfuUDm2rcXbhbj",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 94800,
			unit_amount_decimal: "94800",
		},
		{
			id: "price_1LwTloGUyP9kXnfZdd6ph3or",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666629900,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfpQXEGqW8HjMR",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 49900,
			unit_amount_decimal: "49900",
		},
		{
			id: "price_1LwTloGUyP9kXnfZYdD3yKTd",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1666629900,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MfpQXEGqW8HjMR",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 478800,
			unit_amount_decimal: "478800",
		},
		{
			id: "price_1LspgTGUyP9kXnfZb6JWr3NY",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1665760825,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MSmZds88q8NW8M",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 7900,
			unit_amount_decimal: "7900",
		},
		{
			id: "price_1LjrT4GUyP9kXnfZZLUGWc35",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1663622730,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MSmtLiBhuSPBZ4",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 0,
			unit_amount_decimal: "0",
		},
		{
			id: "price_1LjrK5GUyP9kXnfZMQn2KyAi",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1663622173,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MSmtLiBhuSPBZ4",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 0,
			unit_amount_decimal: "0",
		},
		{
			id: "price_1Ljr7lGUyP9kXnfZQIU4Bg7K",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1663621409,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MSmbL6spRifGKZ",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 478800,
			unit_amount_decimal: "478800",
		},
		{
			id: "price_1Ljr72GUyP9kXnfZf80Nado7",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1663621364,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MSmankcKKjABrd",
			recurring: {
				aggregate_usage: null,
				interval: "year",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 238800,
			unit_amount_decimal: "238800",
		},
		{
			id: "price_1Ljr1oGUyP9kXnfZ3KsAyahq",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1663621040,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MSmbL6spRifGKZ",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 49900,
			unit_amount_decimal: "49900",
		},
		{
			id: "price_1Ljr1XGUyP9kXnfZqDMyPXfk",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1663621023,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MSmankcKKjABrd",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 24900,
			unit_amount_decimal: "24900",
		},
		{
			id: "price_1Ljr0lGUyP9kXnfZQPO8YyNp",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: 1663620975,
			currency: "usd",
			custom_unit_amount: null,
			livemode: true,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "prod_MSmZds88q8NW8M",
			recurring: {
				aggregate_usage: null,
				interval: "month",
				interval_count: 1,
				trial_period_days: null,
				usage_type: "licensed",
			},
			tax_behavior: "exclusive",
			tiers_mode: null,
			transform_quantity: null,
			type: "recurring",
			unit_amount: 3900,
			unit_amount_decimal: "3900",
		},
	],
	has_more: false,
	url: "/v1/prices",
}
export const PaymentLinkDataProd = {
	object: "list",
	data: [
		{
			id: "plink_1MbuRBGUyP9kXnfZqJLkILqp",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/9AQeW2bLyaYYdIQ8yh",
		},
		{
			id: "plink_1MbuRBGUyP9kXnfZhfWeS4ep",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/4gwdRY6re7MM34c3dW",
		},
		{
			id: "plink_1MbuRBGUyP9kXnfZ66NG1S1L",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/8wMaFM6re2ssgV229R",
		},
		{
			id: "plink_1MbuRBGUyP9kXnfZ4U2rq2jn",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/3csbJQbLy6II6goaGm",
		},
		{
			id: "plink_1MbuRBGUyP9kXnfZKzwmplAj",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/4gw8xEcPC9UU0W44hX",
		},
		{
			id: "plink_1MbuRAGUyP9kXnfZET4rEoxd",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/7sI4ho5na8QQgV2bKo",
		},
		{
			id: "plink_1MbuRAGUyP9kXnfZdyHXE0Sn",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/6oEdRY7viffebAI01F",
		},
		{
			id: "plink_1MbuRAGUyP9kXnfZTQDO3CGt",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/6oE3dk8zmgji8owbKm",
		},
		{
			id: "plink_1MbojXGUyP9kXnfZVyqRsv7P",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/6oE7tAbLyebacEMcOp",
		},
		{
			id: "plink_1MbojXGUyP9kXnfZSE9lUcvM",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: null,
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/8wM9BI7vi5EEfQY6q0",
		},
		{
			id: "plink_1Lwa0qGUyP9kXnfZI9nTcFYT",
			object: "payment_link",
			active: true,
			after_completion: {
				redirect: { url: "https://go.teleseer.com/subscription_confirmed" },
				type: "redirect",
			},
			allow_promotion_codes: true,
			application_fee_amount: null,
			application_fee_percent: null,
			automatic_tax: { enabled: true },
			billing_address_collection: "required",
			consent_collection: { promotions: "none", terms_of_service: "none" },
			currency: "usd",
			custom_fields: [],
			custom_text: { shipping_address: null, submit: null },
			customer_creation: "if_required",
			invoice_creation: {
				enabled: false,
				invoice_data: {
					account_tax_ids: null,
					custom_fields: null,
					description: null,
					footer: null,
					metadata: {},
					rendering_options: null,
				},
			},
			livemode: true,
			metadata: {},
			on_behalf_of: null,
			payment_intent_data: null,
			payment_method_collection: "always",
			payment_method_types: null,
			phone_number_collection: { enabled: true },
			shipping_address_collection: null,
			shipping_options: [],
			submit_type: "auto",
			subscription_data: { description: null, trial_period_days: null },
			tax_id_collection: { enabled: true },
			transfer_data: null,
			url: "https://checkout.teleseer.com/b/14kdRYcPC7MM9sA6pW",
		},
	],
	has_more: false,
	url: "/v1/payment_links",
}
